### ISSUE TITLE
asdf-bazel doesn't support 5.0.0 pre-release versions (with easy fix)

### ISSUE THREAD

**Issue by jackwellsxyz** [rajatvig/asdf-bazel#3]
Hi @rajatvig currently asdf-bazel doesn't support 5.0.0 pre-release versions because in list-all, the grep {} range is too small to fit the 5.0.0 prelease names. I changed [this line](https://github.com/rajatvig/asdf-bazel/blob/325f721727c04a0c4b0a432001e1890a66f02d12/bin/list-all#L17) from {1,15} to {1,30} and it is now displaying the 5.0.0 pre-releases and installing them as well.

Happy to submit a PR with this change and/or welcome if you want to make the change yourself.

Thanks!

**Comment by rajatvig** [comment]
Feel free to make the PR. My usage of the plugin has reduced in favor of using `bazelisk`

**Comment by jackwellsxyz** [comment]
Sounds good - I created the PR, and will investigate bazelisk as well.

**Comment by rajatvig** [comment]
Great. Have merged it in
